; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-c3-devkitm-1

[common]
production_build_flags =
  -D WIFI_SSID=\"Network7\"
  -D WIFI_PASSWORD=\"12345678\"
  -D REPORT_URL=\"http://46.224.173.239/report\"
  -D HTTP_API_KEY=\"6cd60369f23504945829520b4e072ab0581bf785164b7babc8a6ca9c8a72fd13\"

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
build_flags =
  ${common.production_build_flags}
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-wroom]
board = esp32dev
build_flags =
  ${common.production_build_flags}

[env:esp32-s3-super-mini]
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
build_flags =
  ${common.production_build_flags}
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
